<?php
// admin.php 后台管理首页

// 确保 session_start() 在任何输出之前调用
session_start();
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

// Debug: 打印会话信息在包含 header.php 之前
error_log("admin.php DEBUG: (Start) SESSION_ID: " . session_id() . ", Before includes. SESSION: " . print_r($_SESSION, true));

// Define ini file path
define('INI_FILE', __DIR__ . '/ini.php');
// 引入白名单函数及全局数组配置文件
if (file_exists("./functions.php")) {
    include("./functions.php");
}

/**
 * Reads the $config array directly from ini.php.
 * This approach is most reliable for the current ini.php structure.
 * @return array The configuration array.
 */
function readIniConfig() {
    $config_data = [];
    error_log("readIniConfig DEBUG: Attempting to read INI_FILE: " . INI_FILE);

    if (file_exists(INI_FILE)) {
        // Temporarily include ini.php to get the $config variable.
        // We use a function scope to avoid variable name collision in global scope.
        // The $config variable will be defined within this local scope.
        // We need to capture it.
        
        // This is a common pattern to include a config file and get its variables
        // without affecting the global scope too much.
        
        // Suppress errors during include in case the file is malformed,
        // we handle errors via file_exists and try-catch for eval if used.
        // For your ini.php structure, a direct include is best.
        
        // Store the current $config (if it exists) to restore it later if needed,
        // although in this function context, it's local.
        $temp_config = [];
        
        // Start output buffering to prevent anything from ini.php from being echoed
        ob_start();
        include INI_FILE;
        ob_end_clean(); // Discard any output from ini.php
        
        // The $config variable defined in ini.php should now be available locally here.
        // We need to ensure it's copied to $temp_config before the function exits.
        if (isset($config) && is_array($config)) {
             $temp_config = $config;
             error_log("readIniConfig DEBUG: Successfully read config from " . INI_FILE . ": " . print_r($temp_config, true));
        } else {
             error_log("readIniConfig ERROR: \$config variable not found or not an array after including " . INI_FILE . ". File content might be malformed.");
        }

        // Return the locally defined $config variable
        return $temp_config;

    } else {
        error_log("readIniConfig ERROR: ini.php not found at " . INI_FILE);
    }
    return $config_data; // Will be empty if file not found or config not read
}

/**
 * Writes the $config array back to ini.php.
 * This function is critical for maintaining all configuration keys.
 * @param array $config_data The complete configuration array to write.
 * @return bool True on success, false on failure.
 */
function writeIniConfig($config_data) {
    // Convert the PHP array to a string representation suitable for direct inclusion.
    // var_export outputs valid PHP code.
    $content = "<?php\n";
    $content .= "// This file is automatically generated by the admin panel.\n";
    $content .= "// DO NOT EDIT MANUALLY unless you know what you are doing.\n";
    $content .= "\$config = " . var_export($config_data, true) . ";\n";
    $content .= "?>";

    error_log("writeIniConfig DEBUG: Attempting to write to INI_FILE: " . INI_FILE . "\nContent to write:\n" . $content);

    if (file_put_contents(INI_FILE, $content, LOCK_EX)) {
        error_log("writeIniConfig DEBUG: Successfully wrote to ini.php.");
        return true;
    } else {
        error_log("writeIniConfig ERROR: Failed to write to ini.php at " . INI_FILE . ". Check file permissions.");
        return false;
    }
}

// Read the current configuration at the very beginning of the script execution
$config = readIniConfig();
// Debug: Confirm $config is properly read initially
error_log("admin.php DEBUG: \$config after initial readIniConfig(): " . print_r($config, true));


// Include header (if it depends on $config, make sure $config is loaded before this)
include("header.php");

//===================================================
// Get dynamic login identifier
// Use null coalescing operator ?? to provide a default value if key doesn't exist
$logged_in_key = $config['login_admin'] ?? 'login_defaul';
error_log("admin.php DEBUG: Derived logged_in_key for login check: " . $logged_in_key);

// Check if user is logged in
if (!(isset($_SESSION['logged_in_admin']) && $_SESSION['logged_in_admin'] === true) && (empty($_SESSION[$logged_in_key]) || $_SESSION[$logged_in_key] !== true)) {
    // If not super admin logged in, and user not logged in, redirect to login page
    error_log("admin.php DEBUG: Login check failed! Redirecting to login.php. Current SESSION state: " . print_r($_SESSION, true) . " | Expected key '" . $logged_in_key . "' not true.");
    header('Location: login.php');
    exit();
}

// Mark admin session as logged in
$_SESSION['admin_logged_in'] = true; // This variable generally denotes "an admin is logged in"
$_SESSION[$logged_in_key] = true; // This is for the specific login key from ini.php

// Debug: Print session info after login check passed
error_log("admin.php DEBUG: Login check passed! Current SESSION state: " . print_r($_SESSION, true));


// --- Handle INI file configuration form submission ---
$message = '';
$messageType = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['action']) && $_POST['action'] === 'update_ini_config') {
        error_log("admin.php DEBUG: Handling 'update_ini_config' POST request.");
        
        // IMPORTANT: Read the current config again just before modifying to ensure
        // we have the most up-to-date values, especially for non-editable keys.
        $current_config_from_file = readIniConfig(); 
        $updated_config = $current_config_from_file; // Start with the full current config

        // Update ONLY the editable keys
        $updated_config['login_admin'] = trim($_POST['login_admin'] ?? $current_config_from_file['login_admin'] ?? '');
        // list_read toggle button value handling
        $updated_config['list_read'] = (isset($_POST['list_read']) && $_POST['list_read'] == '1') ? '1' : '0';
        $updated_config['list_home'] = (isset($_POST['list_home']) && $_POST['list_home'] == '1') ? '1' : '0';
        $updated_config['title'] = trim($_POST['title'] ?? $current_config_from_file['title'] ?? '');
        $updated_config['cover'] = trim($_POST['cover'] ?? $current_config_from_file['cover'] ?? '');

        error_log("admin.php DEBUG: Proposed updated config (only editable fields changed): " . print_r($updated_config, true));

        // 【新增处理】：保存 INI 时同步安全写入白名单状态开关
        $func_file = "./functions.php";
        if (file_exists($func_file)) {
            $func_content = file_get_contents($func_file);
            $form_whitelist_status = (isset($_POST['admin_whitelist']) && $_POST['admin_whitelist'] == '1') ? '1' : '0';
            
            // 预读取旧参数防止污染
            $old_home_url = 'http://192.168.1.10/';
            $old_title = '希米的图册';
            $old_blacklist = 'img.cd,www.img.cd';
            if (preg_match('/\'home_url\'\s*=>\s*[\'"]([^\'"]*)[\'"]/i', $func_content, $m)) { $old_home_url = $m[1]; }
            if (preg_match('/\'title\'\s*=>\s*[\'"]([^\'"]*)[\'"]/i', $func_content, $m)) { $old_title = $m[1]; }
            if (preg_match('/\'admin_blacklist\'\s*=>\s*[\'"]([^\'"]*)[\'"]/i', $func_content, $m)) { $old_blacklist = $m[1]; }
            
            // 提取原本的域名 geturls() 内部原配文本内容，不做任何破坏更改
            $old_geturls_string = "['www.ximi.me','ximi.me','img.cd','www.img.cd', 'img.ximi.me','cdn.ximi.me', '192.168.1.10']";
            if (preg_match('/return\s*(\[.*?\])\s*;/s', $func_content, $matches)) {
                $old_geturls_string = $matches[1];
            }
            
            // 重新重构并生成 functions.php 的底层代码
            $new_func_content = "<?php\n" .
                                "//  ../index_src/defaul/functions.php\n" .
                                "//白名单\n" .
                                "function geturls() {\n" .
                                "    return " . $old_geturls_string . ";\n" .
                                "}\n\n" .
                                "\$config_whitelist = array (\n" .
                                "  'home_url' => '" . addslashes($old_home_url) . "',\n" .
                                "  'title' => '" . addslashes($old_title) . "',\n" .
                                "  'admin_blacklist' => '" . addslashes($old_blacklist) . "',\n" .
                                "  'admin_whitelist' => '" . $form_whitelist_status . "',\n" .
                                ");\n" .
                                "?>";
            @file_put_contents($func_file, $new_func_content);
        }

        if (writeIniConfig($updated_config)) {
            $message = 'INI 配置更新成功！';
            $messageType = 'success';
            // Re-read config after successful write to ensure page displays latest values
            $config = readIniConfig();
            error_log("admin.php DEBUG: INI config updated successfully and re-read for display.");
        } else {
            $message = 'INI 配置更新失败，请检查文件权限！';
            $messageType = 'error';
            error_log("admin.php ERROR: INI config update failed during write operation.");
        }
        // Redirect to prevent form re-submission on refresh
        header("Location: " . $_SERVER['PHP_SELF'] . "?msg=" . urlencode($message) . "&type=" . $messageType);
        exit();
    } elseif (isset($_POST['action']) && $_POST['action'] === 'edit_file_content') {
        error_log("admin.php DEBUG: Handling 'edit_file_content' POST request.");
        // Handle file editor POST requests (your original code logic)
        $filename = $_POST['filename'];
        $new_content = $_POST['content'];

        if (file_put_contents($filename, $new_content)) {
            $message = "文件 '{$filename}' 保存成功！";
            $messageType = 'success';
            error_log("admin.php DEBUG: File '{$filename}' saved successfully.");
        } else {
            $message = "文件 '{$filename}' 保存失败！ Check permissions for '{$filename}'.";
            $messageType = 'error';
            error_log("admin.php ERROR: Failed to save file '{$filename}'.");
        }
        header("Location: " . $_SERVER['PHP_SELF'] . "?msg=" . urlencode($message) . "&type=" . $messageType . "&last_file=" . urlencode($filename));
        exit();
    }
}

// Get message from URL parameters (after redirect)
if (isset($_GET['msg']) && isset($_GET['type'])) {
    $message = htmlspecialchars($_GET['msg']);
    $messageType = htmlspecialchars($_GET['type']);
    error_log("admin.php DEBUG: Message from GET parameters - Msg: '{$message}', Type: '{$messageType}'");
}
$last_file_edited = isset($_GET['last_file']) ? htmlspecialchars($_GET['last_file']) : '';
error_log("admin.php DEBUG: Last file edited (from GET parameter): '{$last_file_edited}'");

?>

<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>后台管理 - Ximi Photo</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; background-color: #f0f2f5; color: #333; line-height: 1.6; padding: 20px; }
        .container { max-width: 960px;width: 100vw; margin: 0; /* Changed from auto to 0 for left align */ background-color: #fff; padding: 30px; border-radius: 10px; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }
        h1, h2, h3, h4 { color: #2c3e50; border-bottom: 2px solid #e0e0e0; padding-bottom: 12px; margin-bottom: 25px; font-weight: 600; }
        h1 { font-size: 2.2em; }
        h2 { font-size: 1.8em; }
        h3 { font-size: 1.4em; }
        h4 { font-size: 1.2em; border-bottom: 1px solid #eee; margin-bottom: 15px; padding-bottom: 8px;}
        a { color: #007bff; text-decoration: none; transition: color 0.2s; }
        a:hover { color: #0056b3; text-decoration: underline; }
        .nav-links a { margin-right: 15px; font-size: 1.1em; }
        form { margin-bottom: 25px; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; background-color: #fdfdfd; }
        label { display: block; margin-bottom: 8px; font-weight: bold; color: #555; }
        input[type="text"], input[type="url"], textarea {
            width: calc(100% - 22px);
            padding: 10px 12px;
            margin-bottom: 15px;
            border: 1px solid #ced4da;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 1em;
            transition: border-color 0.2s, box-shadow 0.2s;
        }
        input[type="text"]:focus, input[type="url"]:focus, textarea:focus {
            border-color: #80bdff;
            box-shadow: 0 0 0 0.2rem rgba(0,123,255,.25);
            outline: none;
        }
        button[type="submit"], input[type="submit"] {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 1em;
            margin-right: 10px;
            transition: background-color 0.3s ease, transform 0.1s ease;
        }
        button[type="submit"]:hover, input[type="submit"]:hover { background-color: #0056b3; transform: translateY(-1px); }
        .message { padding: 12px 20px; margin-bottom: 25px; border-radius: 6px; font-weight: bold; animation: fadeInOut 5s forwards; }
        .message.success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .message.error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }

        @keyframes fadeInOut {
            0% { opacity: 0; }
            10% { opacity: 1; }
            90% { opacity: 1; }
            100% { opacity: 0; }
        }

        /* Toggle Switch for list_read */
        .toggle-switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
            margin-bottom: 15px; /* Adjust margin to align with other inputs */
            vertical-align: middle; /* Align with text */
        }
        .toggle-switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }
        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
            border-radius: 34px;
        }
        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
            border-radius: 50%;
        }
        input:checked + .slider {
            background-color: #2196F3;
        }
        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }
        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }
        /* Round sliders */
        .slider.round {
            border-radius: 34px;
        }
        .slider.round:before {
            border-radius: 50%;
        }
        .toggle-label {
            display: inline-block;
            margin-left: 10px;
            font-weight: normal; /* Override bold for label */
            vertical-align: middle;
        }
        .file-list {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin-bottom: 20px;
            padding-bottom: 15px;
            border-bottom: 1px dashed #eee;
        }
        .file-list a {
            padding: 8px 12px;
            background-color: #e9ecef;
            border-radius: 5px;
            color: #495057;
            text-decoration: none;
            transition: background-color 0.2s, color 0.2s;
        }
        .file-list a:hover {
            background-color: #dae0e5;
            color: #212529;
            text-decoration: none;
        }
        #currentFile {
            font-weight: bold;
            margin-top: 10px;
            display: block;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>后台管理面板</h1>

    <div class="nav-links">
        <a href="admin.php">后台管理</a>
        <a href="logout.php">退出登录</a>
        <a href="./" target="_blank">返回前台</a>
    </div>
    <hr style="margin-top: 15px; margin-bottom: 25px;">

    <?php if ($message): ?>
        <div class="message <?php echo $messageType; ?>">
            <?php echo $message; ?>
        </div>
    <?php endif; ?>

    <h2>INI 文件配置</h2>
    <form action="" method="post">
        <input type="hidden" name="action" value="update_ini_config">

        <label for="login_admin">登录标识 (login_admin):</label>
        <input type="text" id="login_admin" name="login_admin" value="<?php echo htmlspecialchars($config['login_admin'] ?? ''); ?>" required>
        <p class="text-muted">此项用于动态设置登录会话的键名，请确保其安全性。</p>

<label style="margin-bottom: 15px;">
    私密相册设置 (list_read):
    <label class="toggle-switch">
        <input type="checkbox" name="list_read" value="1" <?php echo (isset($config['list_read']) && $config['list_read'] == '1') ? 'checked' : ''; ?>>
        <span class="slider round"></span>
    </label>
    <span id="toggle-label-read" class="toggle-label">
        <?php echo (isset($config['list_read']) && $config['list_read'] == '1') ? '开放浏览' : '设置为私密'; ?>
    </span>
</label>
<p class="text-muted" style="margin-top: 0;">切换以设置相册是否对外开放浏览。</p>

<label style="margin-bottom: 15px;">
    首页轮播图 (list_home):
    <label class="toggle-switch">
        <input type="checkbox" name="list_home" value="1" <?php echo (isset($config['list_home']) && $config['list_home'] == '1') ? 'checked' : ''; ?>>
        <span class="slider round"></span>
    </label>
    <span id="toggle-label-home" class="toggle-label">
        <?php echo (isset($config['list_home']) && $config['list_home'] == '1') ? '开放轮播' : '关闭轮播'; ?>
    </span>
</label>
<p class="text-muted" style="margin-top: 0;">切换以设置相册是否支持首页背景轮播。</p>

<label style="margin-bottom: 15px;">
    安全白名单过滤 (admin_whitelist):
    <label class="toggle-switch">
        <input type="checkbox" name="admin_whitelist" value="1" <?php echo (isset($config_whitelist['admin_whitelist']) && $config_whitelist['admin_whitelist'] == '1') ? 'checked' : ''; ?>>
        <span class="slider round"></span>
    </label>
    <span id="toggle-label-whitelist" class="toggle-label">
        <?php echo (isset($config_whitelist['admin_whitelist']) && $config_whitelist['admin_whitelist'] == '1') ? '开启白名单过滤' : '关闭白名单过滤'; ?>
    </span>
</label>
<p class="text-muted" style="margin-top: 0;">切换以控制 img.php 输出图片时是否启用域名白名单防盗链机制。</p>

        
        <label for="title">相册名称 (title):</label>
        <input type="text" id="title" name="title" value="<?php echo htmlspecialchars($config['title'] ?? ''); ?>" required>

        <label for="cover">相册封面 (cover):</label>
        <input type="text" id="cover" name="cover" value="<?php echo htmlspecialchars($config['cover'] ?? ''); ?>">
        <p class="text-muted">可为空。如果留空，系统将随机获取封面。</p>

        <button type="submit">保存 INI 配置</button>
    </form>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    function loadFile(filename) {
        $.ajax({
            url: 'load_file.php',
            data: { filename: filename },
            method: 'GET',
            success: function(data) {
                $('#content').val(data);
                $('#filename').val(filename);
                $('#currentFile').text('当前文件：' + filename);
                console.log('loadFile: Successfully loaded ' + filename);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                console.error("loadFile Error: Could not load file " + filename + ":", textStatus, errorThrown);
                $('#content').val("无法加载文件内容。请检查文件是否存在或权限是否正确。");
                $('#filename').val(filename);
                $('#currentFile').text('当前文件：' + filename + ' (加载失败)');
            }
        });
    }

    $(document).ready(function() {
        const lastFile = $('#filename').val();
        if (lastFile) {
            loadFile(lastFile);
            console.log('Document Ready: Attempting to load last edited file: ' + lastFile);
        } else {
            console.log('Document Ready: No last edited file to load.');
        }

        // Update toggle label for list_read
        const listReadCheckbox = document.querySelector('input[name="list_read"]');
        const toggleLabelRead = document.getElementById('toggle-label-read');

        function updateReadToggleLabel() {
            if (listReadCheckbox.checked) {
                toggleLabelRead.textContent = '开放浏览';
            } else {
                toggleLabelRead.textContent = '设置为私密';
            }
            console.log('Toggle switch updated: list_read is now ' + (listReadCheckbox.checked ? '1 (开放浏览)' : '0 (设置为私密)'));
        }

        listReadCheckbox.addEventListener('change', updateReadToggleLabel);
        updateReadToggleLabel(); // Initial update

        // Update toggle label for list_home
        const listHomeCheckbox = document.querySelector('input[name="list_home"]');
        const toggleLabelHome = document.getElementById('toggle-label-home');

        function updateHomeToggleLabel() {
            if (listHomeCheckbox.checked) {
                toggleLabelHome.textContent = '开放轮播';
            } else {
                toggleLabelHome.textContent = '关闭轮播';
            }
            console.log('Toggle switch updated: list_home is now ' + (listHomeCheckbox.checked ? '1 (开放轮播)' : '0 (关闭轮播)'));
        }

        listHomeCheckbox.addEventListener('change', updateHomeToggleLabel);
        updateHomeToggleLabel(); // Initial update

        // 【新增改动点】：动态驱动白名单开关的纯 JS 文本切换交互
        const whitelistCheckbox = document.querySelector('input[name="admin_whitelist"]');
        const toggleLabelWhitelist = document.getElementById('toggle-label-whitelist');

        function updateWhitelistToggleLabel() {
            if (whitelistCheckbox.checked) {
                toggleLabelWhitelist.textContent = '开启白名单过滤';
            } else {
                toggleLabelWhitelist.textContent = '关闭白名单过滤';
            }
            console.log('Toggle switch updated: admin_whitelist is now ' + (whitelistCheckbox.checked ? '1 (开启)' : '0 (关闭)'));
        }

        whitelistCheckbox.addEventListener('change', updateWhitelistToggleLabel);
        updateWhitelistToggleLabel(); // 初始化
    });
</script>

</body>
</html>

<?php include("footer.php"); ?>