<?php
// This file is automatically generated by the config editor.
// DO NOT EDIT MANUALLY unless you know what you are doing.

$class = [
  '时尚人像' => 
  [
    '春日私语' => 'gf1',
  ],
  '萌宠世界' => 
  [
    '萌宠' => 'mc',
  ],
  '精美壁纸' => 
  [
    '小清新' => 'xqx',
  ],
];

$config_home = [
  'home_url' => 'https://img.ximi.me',
  'title' => '希米图册',
  'cover' => 'https://img.ximi.me/logo.png',
];

$config_up = [
  'user_xm' => 'admin',
  'pass_xm' => 'admin',
];
?>