<?php
// 后台相册管理与列表 - 动态目录布局优化与批量删除版
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

if (file_exists("./ini.php")) {
    include("./ini.php"); 
}

session_start();

$page_title="图片管理";
// ===================================================
// 1. 扫描 ../user/ 下所有子目录，读取其 ini.php
// ===================================================
$userBaseDir = '../user/';
$albums = []; 

if (is_dir($userBaseDir)) {
    $subDirs = scandir($userBaseDir);
    foreach ($subDirs as $dir) {
        if ($dir === '.' || $dir === '..') continue;
        
        $currentPath = $userBaseDir . $dir;
        if (is_dir($currentPath)) {
            $albumIniPath = $currentPath . '/ini.php';
            if (file_exists($albumIniPath)) {
                // 使用闭包隔离作用域方式安全读取子目录的 $config
                $albumConfig = call_user_func(function($path) {
                    @include($path);
                    return isset($config) ? $config : null;
                }, $albumIniPath);
                
                if ($albumConfig && isset($albumConfig['title'])) {
                    $albums[$dir] = [
                        'title' => $albumConfig['title'],
                        'config' => $albumConfig,
                        'file_path' => $albumIniPath // 记录文件真实路径，方便后续保存写入
                    ];
                }
            }
        }
    }
}

// 决定当前选中的相册目录
$selectedAlbumKey = isset($_POST['target_album']) ? $_POST['target_album'] : (isset($_GET['target_album']) ? $_GET['target_album'] : '');
if (empty($selectedAlbumKey) && !empty($albums)) {
    $selectedAlbumKey = array_key_first($albums);
}

// 动态锁定当前的相册配置和文件路径
$currentAlbumConfig = isset($albums[$selectedAlbumKey]) ? $albums[$selectedAlbumKey]['config'] : null;
$currentAlbumIniPath = isset($albums[$selectedAlbumKey]) ? $albums[$selectedAlbumKey]['file_path'] : null;

// ===================================================
// 2. 鉴权逻辑
// ===================================================
if ($currentAlbumConfig) {
    $logged_in_key = isset($currentAlbumConfig['login_admin']) ? $currentAlbumConfig['login_admin'] : 'logged_in_admin';
    if (!(isset($_SESSION['logged_in_admin']) && $_SESSION['logged_in_admin'] === true) && (empty($_SESSION[$logged_in_key]) || $_SESSION[$logged_in_key] !== true)) {
        header('Location: login.php');
        exit();
    }
} else {
    if (!(isset($_SESSION['logged_in_admin']) && $_SESSION['logged_in_admin'] === true)) {
        header('Location: login.php');
        exit();
    }
}

$_SESSION['admin_logged_in'] = true;

// ===================================================
// 3. 动态设置与路径自动换算（核心：解决群晖 open_basedir 越界）
// ===================================================
$uploadDir          = $currentAlbumConfig ? $currentAlbumConfig['tu_1'] : '';
$thumbnailDir       = $currentAlbumConfig ? $currentAlbumConfig['min'] : ''; 
$largeThumbnailDir  = $currentAlbumConfig ? $currentAlbumConfig['max'] : '';

// 将配置中的 ../../ 动态转换为适应 admin/ 目录的 ../
if ($uploadDir && substr($uploadDir, 0, 6) === '../../') {
    $uploadDir = '../' . substr($uploadDir, 6);
}
if ($thumbnailDir && substr($thumbnailDir, 0, 6) === '../../') {
    $thumbnailDir = '../' . substr($thumbnailDir, 6);
}
if ($largeThumbnailDir && substr($largeThumbnailDir, 0, 6) === '../../') {
    $largeThumbnailDir = '../' . substr($largeThumbnailDir, 6);
}

// ===================================================
// 4. 处理单项与批量删除及表单保存逻辑
// ===================================================
$saveMessage = '';
$saveMessageType = 'success';

// 处理表单保存修改（更新对应相册的 ini.php）
if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['save_config'])) {
    if (empty($currentAlbumIniPath) || !file_exists($currentAlbumIniPath)) {
        $saveMessage = "无法保存：未找到对应的相册配置文件。";
        $saveMessageType = 'error';
    } else {
        $newConfig = $currentAlbumConfig; // 继承旧数据，防止漏掉其他未在表单展现的参数
        
        $newConfig['title']       = isset($_POST['title']) ? trim($_POST['title']) : '';
        $newConfig['login_admin'] = isset($_POST['login_admin']) ? trim($_POST['login_admin']) : 'login_default';
        $newConfig['list_read']   = isset($_POST['list_read']) ? $_POST['list_read'] : '1';
        $newConfig['list_home']   = isset($_POST['list_home']) ? $_POST['list_home'] : '0';
        $newConfig['cover']       = isset($_POST['cover']) ? trim($_POST['cover']) : '';

        $configContent = "<?php\n";
        $configContent .= "// This file is automatically generated by the admin panel.\n";
        $configContent .= "// DO NOT EDIT MANUALLY unless you know what you are doing.\n";
        $configContent .= "\$config = " . var_export($newConfig, true) . ";\n";
        $configContent .= "?>";

        if (@file_put_contents($currentAlbumIniPath, $configContent) !== false) {
            $saveMessage = "相册【" . $newConfig['title'] . "】配置更新成功！";
            $currentAlbumConfig = $newConfig;
            if (isset($albums[$selectedAlbumKey])) {
                $albums[$selectedAlbumKey]['title'] = $newConfig['title'];
                $albums[$selectedAlbumKey]['config'] = $newConfig;
            }
        } else {
            $saveMessage = "保存失败，请检查文件权限：" . $currentAlbumIniPath;
            $saveMessageType = 'error';
        }
    }
}

// 处理单张图片删除
if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['delete_image'])) {
    $imgName = isset($_POST['image_name']) ? basename($_POST['image_name']) : '';
    if ($imgName && !empty($uploadDir)) {
        $targetImg = $uploadDir . $imgName;
        $targetMin = $thumbnailDir . 'min_' . $imgName;
        $targetMax = $largeThumbnailDir . 'max_' . $imgName;

        if (@unlink($targetImg)) {
            @unlink($targetMin);
            @unlink($targetMax);
            $saveMessage = "图片 $imgName 已成功删除。";
        } else {
            $saveMessage = "图片删除失败，请检查权限。";
            $saveMessageType = 'error';
        }
    }
}

// 处理批量删除图片
if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['batch_delete'])) {
    $selectedImages = isset($_POST['images']) ? $_POST['images'] : [];
    if (!empty($selectedImages) && !empty($uploadDir)) {
        $successCount = 0;
        foreach ($selectedImages as $imgName) {
            $imgName = basename($imgName); // 安全过滤
            $targetImg = $uploadDir . $imgName;
            $targetMin = $thumbnailDir . 'min_' . $imgName;
            $targetMax = $largeThumbnailDir . 'max_' . $imgName;

            if (@unlink($targetImg)) {
                @unlink($targetMin);
                @unlink($targetMax);
                $successCount++;
            }
        }
        $saveMessage = "成功批量删除 {$successCount} 张图片（含其缩略图）。";
    } else {
        $saveMessage = "未选中任何图片或路径无效。";
        $saveMessageType = 'error';
    }
}

// 获取换算后的相册图片列表
$images = [];
if (!empty($uploadDir) && is_dir($uploadDir)) {
    $files = scandir($uploadDir);
    if ($files !== false) {
        foreach ($files as $file) {
            if ($file === '.' || $file === '..') continue;
            $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
            if (in_array($ext, ['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'ico'])) {
                $images[] = $file;
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>动态相册配置与列表管理</title>
    <link rel="stylesheet" href="/admin/css/themes.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
        body { font-family: system-ui, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }
        .container { width: 100%; max-width: 1400px; margin: 30px auto; padding: 0 15px; box-sizing: border-box; }
        
        .select-album-box { text-align: center; margin-bottom: 25px; padding: 15px; background: #fff; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
        .select-album-box select { padding: 8px 16px; font-size: 15px; border: 1px solid #ccc; border-radius: 4px; cursor: pointer; outline: none; }
        
        /* 变为通栏全覆盖排版布局 */
        .layout-vertical { display: flex; flex-direction: column; gap: 20px; }
        
        /* 配置区域改为上方横版大卡片 */
        .config-card { background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
        .config-flex-form { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 15px; text-align: left; }
        .config-group { margin-bottom: 5px; }
        .config-group label { display: block; font-weight: bold; margin-bottom: 5px; color: #444; font-size: 14px; }
        .config-group input[type="text"], .config-group select { width: 100%; padding: 8px; box-sizing: border-box; border: 1px solid #ccc; border-radius: 4px; font-size: 14px; }
        .config-footer { margin-top: 15px; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 10px; border-top: 1px solid #eee; padding-top: 15px; }
        
        .btn-submit { background-color: #007bff; color: white; border: none; border-radius: 4px; padding: 10px 25px; font-size: 15px; cursor: pointer; font-weight: bold; }
        .btn-submit:hover { background-color: #0056b3; }
        
        /* 下方图片预览区域 */
        .gallery-card { background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); }
        
        /* 批量操作工具栏 */
        .toolbar { display: flex; justify-content: space-between; align-items: center; background: #f8f9fa; padding: 10px 15px; border-radius: 6px; margin-bottom: 15px; border: 1px solid #eee; }
        .toolbar-left { display: flex; align-items: center; gap: 15px; }
        .btn-batch-delete { background-color: #dc3545; color: white; border: none; padding: 8px 16px; font-size: 14px; border-radius: 4px; cursor: pointer; font-weight: bold; display: flex; align-items: center; gap: 5px; }
        .btn-batch-delete:hover { background: #bd2130; }
        
        /* 图片网格 */
        .image-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 18px; margin-top: 15px; }
        .image-item { border: 1px solid #e2e8f0; border-radius: 6px; overflow: hidden; background: #fafafa; position: relative; display: flex; flex-direction: column; justify-content: space-between; transition: transform 0.2s, box-shadow 0.2s; }
        .image-item:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
        
        /* 复选框美化定位结构 */
        .image-checkbox-wrapper { position: absolute; top: 8px; left: 8px; z-index: 10; background: rgba(255, 255, 255, 0.85); padding: 4px; border-radius: 4px; display: flex; align-items: center; justify-content: center; box-shadow: 0 1px 4px rgba(0,0,0,0.2); }
        .image-checkbox-wrapper input[type="checkbox"] { width: 18px; height: 18px; cursor: pointer; margin: 0; }
        
        .image-item img { width: 100%; height: 140px; object-fit: cover; background: #e9ecef; cursor: pointer; }
        .image-info { padding: 8px; font-size: 13px; color: #4a5568; word-break: break-all; text-overflow: ellipsis; white-space: nowrap; overflow: hidden; border-top: 1px solid #edf2f7; background: #fff; }
        .image-actions { padding: 6px; background: #fff; border-top: 1px solid #edf2f7; }
        
        .btn-delete { background: #f7fafc; color: #e53e3e; border: 1px solid #edf2f7; padding: 5px; font-size: 12px; border-radius: 4px; cursor: pointer; width: 100%; transition: all 0.2s; }
        .btn-delete:hover { background: #fff5f5; color: #c53030; border-color: #feb2b2; }
        
        .no-data { color: #888; padding: 5px 0; font-size: 15px; text-align: center; }
        .select-all-lbl { font-size: 14px; color: #4a5568; cursor: pointer; display: flex; align-items: center; gap: 6px; font-weight: bold; }
        .select-all-lbl input { width: 16px; height: 16px; margin: 0; }
    </style>
</head>
<body>

    <?php include("header.php"); ?>

    <div class="container" style="padding-top: 40px;">
        
        <div class="select-album-box">
            <label style="font-weight: bold; font-size: 16px;">当前管理相册：</label>
            <select id="albumSelector" onchange="location.href='?target_album=' + encodeURIComponent(this.value)">
                <?php if(empty($albums)): ?>
                    <option value="">-- 未检测到任何有效相册 --</option>
                <?php else: ?>
                    <?php foreach ($albums as $key => $album): ?>
                        <option value="<?= htmlspecialchars($key) ?>" <?= $key === $selectedAlbumKey ? 'selected' : '' ?>>
                            <?= htmlspecialchars($album['title']) ?> (<?= htmlspecialchars($key) ?>)
                        </option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>

        <?php if($currentAlbumConfig): ?>
        <div class="layout-vertical">
            
            <div class="config-card">
                <h3 style="margin-top: 0; border-bottom: 1px solid #eee; padding-bottom: 10px; color: #333; font-size: 16px;">⚙️ 修改当前相册配置</h3>
                <form method="POST">
                    <input type="hidden" name="target_album" value="<?= htmlspecialchars($selectedAlbumKey) ?>">
                    
                    <div class="config-flex-form">
                        <div class="config-group">
                            <label>相册名称：</label>
                            <input type="text" name="title" value="<?= htmlspecialchars($currentAlbumConfig['title']) ?>" required>
                        </div>

                        <div class="config-group">
                            <label>独立管理员登录标识：</label>
                            <input type="text" name="login_admin" value="<?= htmlspecialchars($currentAlbumConfig['login_admin']) ?>" required>
                        </div>

                        <div class="config-group">
                            <label>私密状态（游客可看）：</label>
                            <select name="list_read">
                                <option value="1" <?= $currentAlbumConfig['list_read'] == '1' ? 'selected' : '' ?>>公开（游客直接访问）</option>
                                <option value="0" <?= $currentAlbumConfig['list_read'] == '0' ? 'selected' : '' ?>>私密（必须登录才能看）</option>
                            </select>
                        </div>

                        <div class="config-group">
                            <label>首页展示状态：</label>
                            <select name="list_home">
                                <option value="1" <?= $currentAlbumConfig['list_home'] == '1' ? 'selected' : '' ?>>在总首页大厅中公开展示</option>
                                <option value="0" <?= $currentAlbumConfig['list_home'] == '0' ? 'selected' : '' ?>>隐藏（不在首页列出）</option>
                            </select>
                        </div>

                        <div class="config-group">
                            <label>相册封面图文件名：</label>
                            <input type="text" name="cover" value="<?= htmlspecialchars($currentAlbumConfig['cover']) ?>" placeholder="例如: cover.jpg (留空为默认)">
                        </div>
                    </div>

                    <div class="config-footer">
                        <div style="font-size: 12px; color: #888; line-height: 1.5; text-align: left;">
                            <strong>换算路径映射监测：</strong> 
                            原图: <code><?= htmlspecialchars($uploadDir) ?></code> | 
                            缩略图: <code><?= htmlspecialchars($thumbnailDir) ?></code>
                        </div>
                        <button type="submit" name="save_config" class="btn-submit">保存当前相册配置</button>
                    </div>
                </form>
            </div>

            <div class="gallery-card">
                <h3 style="margin-top: 0; border-bottom: 1px solid #eee; padding-bottom: 10px; color: #333; font-size: 16px;">
                    🖼️ 图片管理列表 (共 <?= count($images) ?> 张)
                </h3>
                
                <?php if(empty($images)): ?>
                    <div class="no-data">当前相册内没有任何图片，请前往上传页面添加。</div>
                <?php else: ?>
                    
                    <form id="batchDeleteForm" method="POST">
                        <input type="hidden" name="target_album" value="<?= htmlspecialchars($selectedAlbumKey) ?>">
                        <input type="hidden" name="batch_delete" value="1">

                        <div class="toolbar">
                            <div class="toolbar-left">
                                <label class="select-all-lbl">
                                    <input type="checkbox" id="selectAllCheckbox"> 全选 / 取消全选
                                </label>
                            </div>
                            <div>
                                <button type="button" id="batchDeleteBtn" class="btn-batch-delete">
                                    🗑️ 批量删除选中图片 (<span id="selectCount">0</span>)
                                </button>
                            </div>
                        </div>
                        
                        <div class="image-list">
                            <?php foreach($images as $img): 
                                $minFile = $thumbnailDir . 'min_' . $img;
                                $displayPath = file_exists($minFile) ? $minFile : $uploadDir . $img;
                            ?>
                                <div class="image-item">
                                    <div class="image-checkbox-wrapper">
                                        <input type="checkbox" name="images[]" value="<?= htmlspecialchars($img) ?>" class="img-selector">
                                    </div>

                                    <a href="<?= htmlspecialchars($uploadDir . $img) ?>" target="_blank" title="查看原图">
                                        <img src="<?= htmlspecialchars($displayPath) . '?t=' . time() ?>" alt="缩略图">
                                    </a>
                                    
                                    <div class="image-info" title="<?= htmlspecialchars($img) ?>">
                                        <?= htmlspecialchars($img) ?>
                                    </div>
                                    
                                    <div class="image-actions">
                                        <button type="button" class="btn-delete" onclick="confirmSingleDelete('<?= htmlspecialchars($img) ?>')">永久删除</button>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    </form>
                    
                    <form id="singleDeleteForm" method="POST" style="display:none;">
                        <input type="hidden" name="target_album" value="<?= htmlspecialchars($selectedAlbumKey) ?>">
                        <input type="hidden" name="image_name" id="singleDeleteImgName">
                        <input type="hidden" name="delete_image" value="1">
                    </form>

                <?php endif; ?>
            </div>

        </div>
        <?php else: ?>
            <div class="no-data" style="background: #fff; padding: 25px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.05);">
                未检测到有效的相册，请确认 <code>../user/</code> 目录下存在相册子文件夹且包含正确的 <code>ini.php</code>。
            </div>
        <?php endif; ?>

    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const selectAllCheckbox = document.getElementById('selectAllCheckbox');
            const imgSelectors = document.querySelectorAll('.img-selector');
            const selectCountSpan = document.getElementById('selectCount');
            const batchDeleteBtn = document.getElementById('batchDeleteBtn');
            const batchDeleteForm = document.getElementById('batchDeleteForm');

            if (!selectAllCheckbox) return;

            // 更新选中计数器
            function updateSelectCount() {
                const checkedCount = document.querySelectorAll('.img-selector:checked').length;
                selectCountSpan.textContent = checkedCount;
            }

            // “全选/取消全选” 复选框事件
            selectAllCheckbox.addEventListener('change', function () {
                imgSelectors.forEach(checkbox => {
                    checkbox.checked = selectAllCheckbox.checked;
                });
                updateSelectCount();
            });

            // 监听每个单项复选框的点击
            imgSelectors.forEach(checkbox => {
                checkbox.addEventListener('change', function () {
                    // 如果有一个没选，全选框取消勾选
                    if (!this.checked) {
                        selectAllCheckbox.checked = false;
                    } else {
                        // 如果所有人都勾选了，全选框自动勾选
                        const allChecked = document.querySelectorAll('.img-selector:checked').length === imgSelectors.length;
                        selectAllCheckbox.checked = allChecked;
                    }
                    updateSelectCount();
                });
            });

            // 批量删除按钮触发（SweetAlert2 提示）
            batchDeleteBtn.addEventListener('click', function () {
                const checkedCount = document.querySelectorAll('.img-selector:checked').length;
                if (checkedCount === 0) {
                    Swal.fire({
                        title: '提示',
                        text: '请先勾选需要删除的图片！',
                        icon: 'warning',
                        confirmButtonText: '我知道了'
                    });
                    return;
                }

                Swal.fire({
                    title: '确认批量删除？',
                    text: `您已选中了 ${checkedCount} 张图片，删除后文件及缩略图将永久消失且无法恢复！`,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#dc3545',
                    cancelButtonColor: '#6c757d',
                    confirmButtonText: '确定永久删除',
                    cancelButtonText: '取消'
                }).then((result) => {
                    if (result.isConfirmed) {
                        batchDeleteForm.submit();
                    }
                });
            });
        });

        // 单项删除函数
        function confirmSingleDelete(imgName) {
            Swal.fire({
                title: '确认删除？',
                text: `确定要永久删除图片 "${imgName}" 吗？（对应的缩略图也将被同步清理）`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#dc3545',
                cancelButtonColor: '#6c757d',
                confirmButtonText: '确定删除',
                cancelButtonText: '取消'
            }).then((result) => {
                if (result.isConfirmed) {
                    document.getElementById('singleDeleteImgName').value = imgName;
                    document.getElementById('singleDeleteForm').submit();
                }
            });
        }
    </script>

    <?php if(!empty($saveMessage)): ?>
    <script>
        Swal.fire({
            title: '<?= $saveMessageType === "success" ? "操作成功" : "操作提示" ?>',
            text: '<?= addslashes($saveMessage) ?>',
            icon: '<?= $saveMessageType ?>',
            confirmButtonText: '确定'
        });
    </script>
    <?php endif; ?>
</body>
</html>