<?php
// admin.php 后台默认首页
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$page_title = "首页配置"; 

session_start();

// 检查用户是否已登录
if (empty($_SESSION['logged_in_admin']) || $_SESSION['logged_in_admin'] !== true) {
    header('Location: login.php');
    exit();
}

$_SESSION['admin_logged_in'] = true;

$userMessage = '';
$userMessageType = ''; 

if (isset($_GET['msg']) && isset($_GET['type'])) {
    $userMessage = htmlspecialchars($_GET['msg']);
    $userMessageType = htmlspecialchars($_GET['type']);
}

// 引入配置文件路径常量
define('SETING_FILE', __DIR__ . '/../index_src/ini/seting.php');

// 引入当前的配置文件数据
if (file_exists(SETING_FILE)) {
    include(SETING_FILE);
}

// 兜底防错变量初始化
if (!isset($class) || !is_array($class)) $class = [];
if (!isset($config_home) || !is_array($config_home)) $config_home = [];
if (!isset($config_up) || !is_array($config_up)) $config_up = ['user_xm' => 'ximi', 'pass_xm' => 'admin'];

// ==========================================
// 核心逻辑 A：处理主页配置更新
// ==========================================
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'update_config') {
    // 剔除掉多余的 admin_whitelist 参数
    $new_config_home = [
        'home_url' => rtrim(trim($_POST['home_url']), '/'),
        'title' => trim($_POST['title']),
        'cover' => trim($_POST['cover'])
    ];

    if (writeConfig($class, $new_config_home)) {
        header("Location: admin.php?msg=" . urlencode("主页配置更新成功！") . "&type=success");
        exit();
    } else {
        $userMessage = "主页配置更新失败，请检查文件权限！";
        $userMessageType = "error";
    }
}

// ==========================================
// 核心逻辑 B：修改用户密码功能
// ==========================================
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'update_password') {
    $new_user = trim($_POST['user_xm']);
    $new_pass = trim($_POST['pass_xm']);

    if (empty($new_user) || empty($new_pass)) {
        $userMessage = "用户名或密码不能为空！";
        $userMessageType = "error";
    } else {
        if (writeUserConfig($new_user, $new_pass)) {
            $config_up['user_xm'] = $new_user;
            $config_up['pass_xm'] = $new_pass;
            header("Location: admin.php?msg=" . urlencode("密码修改成功！") . "&type=success");
            exit();
        } else {
            $userMessage = "密码修改失败，请检查文件写权限！";
            $userMessageType = "error";
        }
    }
}

/**
 * 💡 彻底修复：数组美化时 `]` 被误改问题
 * 核心逻辑：精准切割提取，不使用任何带有盲区盲伤的正则美化
 */
function writeConfig($class_data, $config_home_data) {
    if (!file_exists(SETING_FILE)) return false;

    $content = @file_get_contents(SETING_FILE);
    if ($content === false) return false;

    // 1. 提取出绝对不能动、不属于我们管辖的 $config_up 的完整原始代码块
    $up_block = '';
    $up_pattern = '/\$config_up\s*=\s*\[.*?\s*\]\s*;|\$config_up\s*=\s*array\s*\(.*?\)\s*;/s';
    if (preg_match($up_pattern, $content, $matches)) {
        $up_block = $matches[0];
    } else {
        global $config_up;
        $up_block = '$config_up = ' . var_export($config_up, true) . ';';
    }

    // 2. 转换成标准的现代化短数组字符串
    $class_str = '$class = ' . var_export($class_data, true) . ';';
    $home_str = '$config_home = ' . var_export($config_home_data, true) . ';';

    $clean_arrays = "<?php\n\n" . $class_str . "\n\n" . $home_str . "\n\n?>";
    $clean_arrays = preg_replace('/array\s*\(\s*\)/s', '[]', $clean_arrays);
    $clean_arrays = str_replace("array (\n", "[\n", $clean_arrays);
    $clean_arrays = preg_replace('/^(\s*)\)(,?)$/m', '$1]$2', $clean_arrays);
    $clean_arrays = preg_replace('/^(\s*)\);$/m', '$1];', $clean_arrays);

    $clean_arrays = str_replace(["<?php", "?>"], "", $clean_arrays);
    $clean_arrays = trim($clean_arrays);

    // 3. 终极无污染拼装
    $final_file_content = "<?php\n" .
                          "// This file is automatically generated by the config editor.\n" .
                          "// DO NOT EDIT MANUALLY unless you know what you are doing.\n\n" .
                          $clean_arrays . "\n\n" .
                          $up_block . "\n?>";

    return @file_put_contents(SETING_FILE, $final_file_content, LOCK_EX) !== false;
}

/**
 * 精准修改管理员账户数组 $config_up，绝不影响其他变量
 */
function writeUserConfig($username, $password) {
    if (!file_exists(SETING_FILE)) return false;
    $content = @file_get_contents(SETING_FILE);
    if ($content === false) return false;

    $up_data = ['user_xm' => $username, 'pass_xm' => $password];
    $up_string = '$config_up = ' . var_export($up_data, true) . ';';

    $up_string = str_replace("array (\n", "[\n", $up_string);
    $up_string = preg_replace('/^(\s*)\)(,?)$/m', '$1]$2', $up_string);
    $up_string = preg_replace('/^(\s*)\);$/m', '$1];', $up_string);

    $up_pattern = '/\$config_up\s*=\s*\[.*?\s*\]\s*;|\$config_up\s*=\s*array\s*\(.*?\)\s*;/s';
    if (preg_match($up_pattern, $content)) {
        $content = preg_replace($up_pattern, $up_string, $content);
    } else {
        if (strpos($content, '?>') !== false) {
            $content = str_replace('?>', $up_string . "\n\n?>", $content);
        } else {
            $content .= "\n\n" . $up_string;
        }
    }

    return @file_put_contents(SETING_FILE, $content, LOCK_EX) !== false;
}

// 🧱 载入你的全局 header.php（其中已包含侧边栏，并且会打开主内容容器 div）
include("header.php"); 
?>

<style>
    .config-card {
        background: rgba(255, 255, 255, 0.65);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        border: 1px solid rgba(255, 255, 255, 0.4);
        border-radius: 16px;
        padding: 25px;
        margin-bottom: 25px;
        box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.05);
    }
    .card-title {
        font-size: 18px;
        color: #333;
        margin-top: 0;
        margin-bottom: 20px;
        font-weight: 600;
        display: flex;
        align-items: center;
        gap: 8px;
    }
    .form-group {
        margin-bottom: 18px;
    }
    .form-group label {
        display: block;
        font-size: 13px;
        color: #555;
        margin-bottom: 8px;
        font-weight: 500;
    }
    .form-group input[type="text"],
    .form-group input[type="password"],
    .form-group input[type="url"] {
        width: 100%;
        padding: 10px 14px;
        border: 1px solid rgba(0, 0, 0, 0.12);
        border-radius: 8px;
        background: rgba(255, 255, 255, 0.9);
        font-size: 14px;
        color: #333;
        outline: none;
        transition: all 0.25s ease;
    }
    .form-group input:focus {
        border-color: #667eea;
        box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.15);
        background: #fff;
    }
    .btn-submit {
        background: linear-gradient(135deg, #4f46e5 0%, #3b82f6 100%);
        color: #fff;
        border: none;
        border-radius: 8px;
        padding: 11px 22px;
        font-size: 14px;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.25s ease;
        box-shadow: 0 4px 12px rgba(79, 70, 229, 0.15);
    }
    .btn-submit:hover {
        opacity: 0.95;
        transform: translateY(-1px);
        box-shadow: 0 6px 16px rgba(79, 70, 229, 0.25);
    }
    .btn-submit:active {
        transform: translateY(0);
    }
</style>

<div class="config-card">
    <h2 class="card-title">🌐 主页基本配置</h2>
    <form method="post">
        <input type="hidden" name="action" value="update_config">
        
        <div class="form-group">
            <label>系统主页 URL 路径</label>
            <input type="url" name="home_url" value="<?= htmlspecialchars($config_home['home_url'] ?? '') ?>" placeholder="例如: http://192.168.1.10/xm" required>
        </div>
        
        <div class="form-group">
            <label>站点全局主标题</label>
            <input type="text" name="title" value="<?= htmlspecialchars($config_home['title'] ?? '希米图册') ?>" required>
        </div>
        
        <div class="form-group">
            <label>站点徽标 Logo 网址</label>
            <input type="text" name="cover" value="<?= htmlspecialchars($config_home['cover'] ?? '') ?>" placeholder="图片URL相对或绝对路径">
        </div>

        <button type="submit" class="btn-submit">💾 保存主页配置</button>
    </form>
</div>

<div class="config-card">
    <h2 class="card-title">🔐 管理员账号密码修改</h2>
    <form method="post">
        <input type="hidden" name="action" value="update_password">
        
        <div class="form-group">
            <label>后台管理用户名</label>
            <input type="text" name="user_xm" value="<?= htmlspecialchars($config_up['user_xm'] ?? 'ximi') ?>" required autocomplete="off">
        </div>
        
        <div class="form-group">
            <label>后台管理密码</label>
            <input type="password" name="pass_xm" value="<?= htmlspecialchars($config_up['pass_xm'] ?? 'admin') ?>" placeholder="请输入新密码" required autocomplete="new-password">
        </div>

        <button type="submit" class="btn-submit" style="background: linear-gradient(135deg, #6366f1 0%, #a855f7 100%); box-shadow: 0 4px 12px rgba(99, 102, 241, 0.15);">🔑 确认修改账户信息</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<?php if(!empty($userMessage)): ?>
<script>
    Swal.fire({
        title: '提示消息',
        text: '<?= $userMessage ?>',
        icon: '<?= $userMessageType === "success" ? "success" : "error" ?>',
        confirmButtonText: '确定'
    });
</script>
<?php endif; ?>

</body>
</html>